# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20161022_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
