# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20161022_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
