# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('location', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=200)),
                ('min_volunteers', models.IntegerField()),
                ('max_volunteers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventXUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eid', to='user.Event')),
                ('uId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventxuser',
            unique_together=set([('uId', 'eId')]),
        ),
    ]
