# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20161022_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='location',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
